name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.sys.os }} 
    strategy:
      matrix:
        sys: 
          - { name: linux-glibc, os: ubuntu-latest,  shell: bash }
          - { name: linux-musl,  os: ubuntu-latest,  shell: 'alpine.sh --root {0}' }
          - { name: windows,     os: windows-latest, shell: pwsh }
          - { name: mac,         os: macos-latest,   shell: bash }
    defaults:
      run:
        shell: ${{ matrix.sys.shell }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    
    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@39d2d96fa8e4b713be89c0239a5c3b9a0f49838d
      if: ${{ matrix.sys.name == 'linux-musl' }}
      with:
        arch: x86_64
        packages: >
          make
          cmake
          libstdc++
          g++
          musl-dev
          git

    - name: Git Nonsense
      if: ${{ matrix.sys.os == 'ubuntu-latest' }}
      run: git config --global --add safe.directory ${{github.workspace}}

    - name: Configure CMake
      env:
        USE_MUSL_LIBC: ${{ matrix.sys.name == 'linux-musl' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_MUSL_LIBC=${{env.USE_MUSL_LIBC}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
